#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/04
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-04-24 三 17:39]
#+TITLE: 线性代数第六章——二次型
#+HUGO_TAGS:
#+HUGO_CATEGORIES: exam math
#+LATEX_HEADER: \usepackage{amsmath}
#+HUGO_CUSTOM_FRONT_MATTER: :image https://r2.guolongji.xyz/allinaent/2024/06/e0dd48553ae47b1f7a78c4e75f4f0763.jpg

* 二次型的定义、矩阵表示，合同矩阵

一、二次型的概念

在 $\mathbb{R}^{n}$ （每个元素是个实数 n 维向量）上的一个二次型是定义在 $\mathbb{R}^{n}$ 上的函数，
表达式为 $Q(x)=x^{T}Ax$ ，其中 A 是一个 $n \times n$ 对称矩阵（重点）。

最简单的一个二次型是 $Q(x) = x^{T}Ix = ||x||^{2}$ , $Q(x)$ 称为二次型 f 的对应矩阵。


* 化二次型为标准型、规范形、合同二次型

一、标准型的概念：若二次型 $f(x_{1},x_{2},...,x_{n})$ 只有平方项，没有混合项，即为标准型。

二、规范型的概念：若在标准型当中，平方项的系数只是 1, -1, 0 ，则称为二次型。
1 的个数是 p 个，-1 的个数是 q 个，0 的个数是 n-(p+q) 即 n-r 个。

三、化二次型为标准形，规范型

定理：对任意一个 n 元二次型 $f(x_{1},x_{2},...,x_{n})=x^{T}Ax$ ，必存在正交变换 $x=Qy$ ，其中
$Q$ 是正交矩阵，化二次型为标准型，即：

$$f(x_{1},x_{2},...,x_{n})=x^{T}Ax
\xlongequal {x=Cy}y^{T}Q^{T}AQy=\lambda_{1}y_{1}^{2}+\lambda_{2}y_{2}^{2}+...+\lambda_{n}y_{n}^{2}$$

其中 $\lambda_{1},\lambda_{2},...,\lambda_{n}$ 是 $A$  的 n 个特征值。（$\lambda_{i}$ 是 r 重特征值，则计为 r
个特征值）

定理：任一个 n 元二次型 $f(x_{1},x_{2},...,x_{n})=x^{T}Ax$ ，都可以通过（配方法）可逆线性变换
$x=Cy$ ，其中 C 是可逆阵，化为标准形。即：
$$f(x_{1},x_{2},...,x_{n})=x^{T}Ax \xlongequal{x=Cy}
y^{T}C^{T}ACy=d_{1}y_{1}^{2}+d_{2}y_{2}^{2}+...+d_{n}y_{n}^{2}$$

四、合同矩阵、合同二次型

合同的概念：设 A, B 是两个 n 阶方阵，若存在可逆阵 C ，使得 $C^{T}AC=B$ ，则称 A 合同于 B
记成 $A\simeq B$

惯性定理：对某个二次型，作可逆线性变换化成标准形（或规范形），所作的可逆线性变换不唯一，标准型
也不唯一，但其标准形中正平方项的项数 p ，负平方项的项数 q 都是由所绐二次型唯一确定的。

正平方项的项数 p 称为正惯性指数，负平方项的项数 q 称为负惯性指数，$p+q=r$ 是二次型对应矩
阵的秩， $p-q$ 称为符号差。

这块不是很懂，可以单独看视频加深理解。

定理：实对称阵 A, B 合同的充要条件是：实对称阵 $A\simeq B$ $\Leftrightarrow x^{T}Ax$ 与 $x^{T}Bx$ 有相同的正、
负惯性指数。实对称阵 A,B 合同的必要条件是 A,B 有相同的秩，即 $A\simeq B$ $\Rightarrow$ $r(A)=r(B)$


* 正定二次型、正定矩阵

正定的定义：若对于任意的非零向量 $x=[x_{1},x_{2},...x_{n}]^{T}$ ，恒有二次型大于 0 。则称之为正定
二次型，其对应的矩阵是正定矩阵。

定理：可逆线性变换不改变不改变二次型的正定性

定理： f 正定的充要条件

$f(x_{1},x_{2},...,x_{n})=x^{T}Ax$ 正定 $\Leftrightarrow$ A 的正惯性指数 $p=r=n$ （r 是 A 的秩，n 是未知
量个数） $A\simeq E$ ，即存在可逆阵 C ，使得 $C^{T}AC=E$ $\Leftrightarrow$ $A=D^{T}D$ ，其中 D 是可逆阵
$\Leftrightarrow$ A 的全部特征值 $\lambda_{i}>0,i=1,2,...,n$ $\Leftrightarrow$ A 的全部顺序子式大于零（即从左
上角到右下角的子方阵大于零）

定理：$f=x^{T}Ax$ 正定的必要条件

1. A 的对角线元素 $a_{ii}>0$
2. A 的行列式 $|A|>0$


目前第一遍概念公式的浏览结束了，第一遍的学习比较粗糙，后面还会做两遍题，并画一些思维导图。

