#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/04
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-04-08 一 00:26]
#+TITLE: 线性代数第三章——向量
#+HUGO_TAGS:
#+HUGO_CATEGORIES: exam

* n 维向量的概念与运算

- 概念
 + n 维向量
 + 零向量
 + 运算
  - 加法
  - 数乘
  - 内积（各个分量相乘并相加）

向量的加法，数乘满足交换率，结合率，分配率。

* 线性表出、线性相关

- 概念
 + 线性组合（m 个 n 维向量 $k_{1}\alpha_{1}+k_{2}\alpha_{2}+...+k_{m}\alpha_{m}$ 称为向量组的一个线性组合，
   $k_{1}...K_{m}$ 称为组合系数
 + 线性表出（线性组合就是 $\beta$ ，可由 $\alpha_{1},\alpha_{2}...,\alpha_{m}$ 线性表出；定义二，若两个向量组，
   一个当中的任意一个向量都可以由另一个向量组的向量线性表出，则称向量组一可由向量组二线性表出。
 + 线性相关、线性无关（当且仅当系数全为零时 $k_{1}\alpha_{1}+k_{2}\alpha_{2}+...+k_{m}\alpha_{m}=0$ ，则称之
   为线性相关，否则为线性无关
- 重要定理
 + 线性相关则齐次方程组有非零解，秩 $r(\alpha_{1},\alpha_{2},\alpha_{3},...,\alpha_{s})<s$
 + 线性相关则行列式 $|\alpha_{1},\alpha_{2},...,\alpha_{n}|=0$
 + n+1 个 n 维向量必线性相关
 + 若 n 维向量组线性无关，则向量组的延伸组必线性无关
 + n 维向量 $\beta$ 可由向量组表出则非齐次方程组有解，秩
   $r(\alpha_{1},\alpha_{2},...,\alpha_{mf}=r(\alpha_{1},\alpha_{2},...,\alpha_{m},\beta)$
 + 向量组线性相关，至少有一个向量 $\alpha_{i}$ 可以由其余 s-1 个向量线性表出
 + 向量组 $\alpha_{1},\alpha_{2},...\alpha_{s}$ 线性无关，而 $\alpha_{1},\alpha_{2},...,\alpha_{s},\beta$ 线
   性相关，则向量 $\beta$ 可由 $\alpha_{1},\alpha_{2},...,\alpha_{s}$ 线性表出，且表示法唯一。
 + 若 $I$ （s 个向量） 能被 $II$ （ t 个向量） 线性表出，且 $s > t$ ，则
   $\alpha_{1},\alpha_{2},...,\alpha_{s}$ 必线性相关
 + 若 n 维向量组 $\alpha_{1},\alpha_{2},...\alpha_{s}$ 线性无关，可由 $\beta_{1},\beta_{2},...,\beta_{t}$ 线
   性表出，则 $s \leq t$

* 极大线性无关组、秩

- 概念 用人话说就是向量组再多添一个任意向量就会让新的向量组线性相关，而极大无关组中向量的个数则称为秩。
- 有关秩的定理

如果向量组 I 可由 II 线性表出。则 $r(\uppercase\expandafter{\romannumeral1}) \leq r(\uppercase\expandafter{\romannumeral2})$

如果向量组等价，则秩相等。

行向量的秩等于列向量的秩。

经初等变换向量组的秩不变。

* Schmidt 正交化、正交矩阵

正交化的意思是将线性无关正交系转化为正交系的过程。这个有一个统用的方法，看起来很简单，
却能够以一个人的名字命名。

$\beta_{1} = \alpha_{1}$

$\beta_{2}=\alpha_{2}-\frac{(\alpha_{2},\beta_{1})}{(\beta_{1},\beta_{1})}\beta_{1}$

$\beta_{3}=\alpha_{3}-\frac{(\alpha_{3},\beta_{1})}{(\beta_{1},\beta_{1})}\beta_{1}
-\frac{(\alpha_{3},\beta_{2})}{(\beta_{2},\beta_{2})}\beta_{1}$

再单位化。 $\gamma_{1}=\frac{\beta_{1}}{|\beta_{1}|}$  ，$\gamma_{2}$ ， $\gamma_{3}$ 同理。

** 正交矩阵

正交矩阵是方块矩阵，行向量和列向量皆为正交的单位向量。这句话太经典了。

有以下的公式满足： $AA^{T}=A^{T}A=E$

$A^{T}=A^{-1}$

$|A|=1$ 或者 $-1$

矩阵和行列式都是更高维的一堆数的规律的知识。更高级的就是集合论的群、域、环，这些更为抽象的知识。

[[pdf:~/mydata/orgmode/gtd/2021李永乐复习全书【数学二】.pdf::265++0.99][正交矩阵]]

