#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/05
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-05-07 二 11:02]
#+TITLE: 威联通使用ipv6 加ddns 进行远程访问
#+HUGO_TAGS:
#+HUGO_CATEGORIES: technology


* 首先要开启 ipv6

https://post.smzdm.com/p/ar678qwz/

我家的光猫是新的。需要网上百度一下对应光猫型号的用户和密码。

开起的过程也比较麻烦，算是了解一下 ipv6 的基本设置情况。


* 群晖使用 ipv6 加 ssl 访问

https://www.youtube.com/watch?v=MjKfcNihwU8

这个使用方法就是免费的，快速的。效果非常地好。


* 威联通 qnap 使用 ipv6 加 ssh 的访问

国区的帐号也可以申请 let's encrypt 的 ssl 证书了。

https://post.smzdm.com/p/am3egqnd/

威联通使用的视频在这里：

https://www.youtube.com/watch?v=IMMZ1MIQrWE

* 机器的安全性

https://www.suncan.com.cn/archives/8029

暴露在公网中的机器都有可能受到攻击，最好的办法是针对特征做好安全。不使用 root，admin
账号，并禁用。还有一般禁用 ssh，而且打开 ssh 也不要用默认的 22 端口号。

使用 ssl 连接。还有更新安全漏洞的补丁。恩，最好的就是把密码改成自己都觉得太复杂太难记
的东西，这一点太重要了，不要为了省事，在密码长度上有水份。

想让为了自己方便费时费电的 nas 变成黑客的肉鸡吗？不想的话，就认真对待安全这件最重要的
事情上。

* 实践

上面的内容都是意想，下面是实践中遇到的问题。

我的光猫是移动吉比特光猫 SK-D746

我的路由器是红米 AX6000

步骤：

+ https://www.dujin.org/22396.html

通过这篇博客可以获取到光猫的超级管理员密码。

+ 将光猫设置不桥接。

桥接模式是绐专家用的，好在我也算一个专家。

这一步是通过一个 bilibili 的视频学习到的。

https://www.bilibili.com/video/BV1Va4y1B77y/

这位网管大佬的视频讲解地非常地好。


+ ipv6 dns 获取不正常的问题

https://douyin.com/shipin/7266390792045135884

ipv6 的好处，可以看 ipv6 的直播。

ipv6 是黑科技。

ipv6 其水甚深。

ipv6 用手机热点绐电脑上网，通过有的手机，电脑可以获得 ipv6 地址；而另外一些则不行。
像这类的问题，ipv6 在这个世界中的成熟度还是不好的。是需要探索的。

电视的影视仓中就有 ipv6 的直播源，效果要比 ipv4 的好很多，换台流畅且不卡顿。

+ 2 兆的威联通自带的远程访问一些简单的需要也是可以满足的。但是绝对不是最好的
实践。

https://zhihu.com/question/588601915

很多公司的内网不支持 ipv6 地址的原因。

我的域名 guolongji.xyz 在 2024 年 9 月 29 日到期。续订的费用居然要 146 块钱。那我还不如花
个 10 几块钱换个域名。先把之前的 ddns 规则拍照记录一下。为了省心的话其实花个 100 块钱也
还行。

+ 最佳的实践方案，网上有那么多乐于分享的人，我是没有想到的。

https://zhihu.com/question/571808168

+ qnap 的客服非常好

+ lucky 这个软件很好

https://lucky666.cn/

今天晚上一定要把公网访问弄好，这太重要了。

https://post.smzdm.com/talk/p/akkzmmn9/

光猫上的 dhcpv6 服务也需要关闭，不然会跟路由器的 dhcpv6 服务冲突，另外光猫的 RA 配置也得取消 M O 的勾选。

+ ipv6 下的一些基础知识：

https://zhuanlan.zhihu.com/p/583128466

第一种：获得 IPv6 地址的同时获得 PD 地址

推荐方案：禁用 dhcpv6 和 ndp，启用 RA（无标记）和 slaac 。

NDP（Neighbor Discovery Protocol，邻居发现协议）是 IPv6 的一个关键协议，它组合了 IPv4 中的 ARP、ICMP 路
由器发现和 ICMP 重定向等协议，并对它们作了改进。 作为 IPv6 的基础性协议，NDP 还提供了前缀发现、邻居不
可达检测、重复地址监测、地址自动配置等功能。

什么是 slaac 呢？

SLAAC 可提供即插即用 IP 连接，而无需手动配置主机，从而简化 IPv6 地址管理。 SLAAC 允许 IPv6 客户端使用本
地可用信息和路由器通过邻居发现协议（NDP） 通告的信息组合生成自己的地址。 NDP 消息不安全，这使得 SLAAC 容
易受到涉及链路层地址欺骗（或伪造）的攻击。

总的来说，光猫和路由器也就那么几个设置而已。我认为试不了几次，ipv6 就能使用了。最后，qnap 安装 lucky
后。

https://zhihu.com/question/588601915 用 cloudflare 做 ssl 证书和 ddns ，这样的话。就可以利用手机送的
移动 50 M 的上行带宽。

* 关于分享

可以用阿里云的 webdav 来分享 Nas 中的数据绐别人。用 Nas 这个硬件我学会了很多的东西。后面多花些时间
在真正能提高自己内功的方面吧。

* ipv6 电视直播源并不好用

如果不是网络拓扑图没想到电视家倒闭。其实我做了桥接。不知道小米路由器支持 iptv 否？因为我的光猫是有单独的 iptv
口的。所以可能还是要走线，那就很丑了。

** 看电视的方案一

移动的单线复用方案：

https://github.com/ruur/cmcc-iptv

这个要接一个移动的魔百盒电视盒子。这个方案大概率是能够成功的，但是也不能保证 100% 能成功。而且我最终的
目的就是看电视，而不是看 4k 电影。所以买电视盒子，后面的 vip 视频还是要付费的。所以直接搞 iptv 是不错的。

** 看电视的方案二

购买 apple tv 的电视盒子。

** 购买一个支持 ipv6 的 android 的电视盒子

因为小米电视是不支持 ipv6 的，不能看 ipv6 的直播源。

中央 3 ，6 ，8 台是不能观看的。因为这三个台是 vip 的。就算下载了央视频也是不能看的。

经过我不懈的努力，我终于证明了 IPv6 的 IPTV 源也是无法找到稳定可用的，在手机上就无法正常播放。所以不要再
折腾这块了。

直接用 my-tv 那个应用，除了 3 ，5 ， 6 ，8 这几个 cctv 的频道，有不少能看的了，知足吧。

* 阿里云 webdav 会不会封号

https://www.cnblogs.com/xyztank/articles/17073846.html

电脑，nas 和手机都可以挂载 webdav 磁盘。如果不封号是没问题的。但是有封号风险，所以我就不弄了，直接
把 aliyun 当成一个数据备份的地方算了。不折腾！


* 将 go-daddy 上的域名转到 cloudflare 上

https://macin.org/2024/04/20/transdomain-from-godaddy2cloudflare/

这个是能省钱的，这件事必须做且一定能完成。转移域名需要先解锁域名，我把 godaddy 上的域名解锁了。
还要等待几个小时。完成域名的转移可能需要几天时间，但是可以每年节省 13 usd ，也就是将近一百块钱。
而且用的合适了之后。域名就一直用这个了。

很多事情就是这样的，想快快不起来，有很多的流程是在别人的手上的。

整体转移的过程很顺利，几个小时批准完成就好了 10.18 美元，也就 70 多人民币。打开
自动续订。完美，这个域名我可以一直保留着了。

* 总结

总共就两个步骤，一个是打开 ipv4/ipv6 双通道，使用光猫播号，路由器 ipv6 桥接。

第二个步骤是打开威联通的免费 ssl 证书，通过 ddns 用威联通的域名来访问 nas 设
备。有了这个就太方便了，随时可以把重要的资料备份到自己的 nas 当中。ssl 的安全性
是一定程度上能保证的。但是最好也不要用 admin 帐号进行访问。
