#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/04
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-04-08 一 23:08]
#+TITLE: 在终端下使用 emacs
#+HUGO_TAGS:
#+HUGO_CATEGORIES: emacs

emacs 的插件简直太多了。很多没用到但是写了一堆无用代码，定位一个新的 bug 就难了。GUI 的 emacs
和 TUI 的 emacs 各有优劣。 GUI 下的 emacs 可以图文混排，latex ，orgmode ，公
式，图片实时渲染。但是 GUI 的 emacs-vterm 终端模拟器用 tmux 有无法转义，体验的
流畅性不足。

所以写博客，用 GUI 。

看代码，写代码，用 TUI 。

打开文件，用终端下的 emacsclient

* 错误修改

第一个错误：

#+begin_src lisp
;; 这个会引起终端下鼠标划动不断出现转义序列导致无法使用！！！
;;(global-set-key (kbd "M-[") 'ggtags-find-tag-dwim)
#+end_src

第二个错误：

#+begin_src lisp
;; 这个会导致终端下的 dired-mode 无法使用
;;'(dired-listing-switches "-alFh")
#+end_src

这两个错误都是通过代码二分找的，写在少数的配置文件当中就一点好处，好排错。

* 与 tmux 配合

快捷键定义无冲突即可。

emacs --daemon=foo 运行守护进程，但是有多个 global gtags 的情况下。一个 server 是
不对的。emacsclient -nw -s foo  来指定 server 。

其实可以这样，桌面程序 server-name 用 server1 server2 server3 server4 server5 。
用脚本 E1 E2 E3 E4 E5 来起动。

tui 的 server-name 用 s1 s2 s3 s4 s5 ，命令是 e1 e2 e3 e4 e5 。数量绝对够了。

多个 tmux 的 session ，session 名字和 tui 代码的 server-name 对应。这只是一个想法
当然命令都可以手动来敲。

** 升级

比如我 p1 ~/gh/blog/ 打开一个项目，用 e1 就是对应的 server 用 emacsclient 打开。
这是最好的方法，一键打开。tmux 的实力也能全部发挥出来了，非常棒！！！

* dirvish

这个插件在 tui 下没有问题。另外用“ (”来打开和关闭 dired 显示的细节，非常好。
以后看代码的效率一定会非常地高。

* 总结

说起来很复杂，用起来可以不断优化。

事以密成，言以泄败。所以没有放下的，不要说出来。说出来多数是放下了。多领悟生活的
智慧，或许有一天你真的会因此受益。
