#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/04
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-04-07 日 00:16]
#+TITLE: 论心态对人生的重要性
#+HUGO_TAGS:
#+HUGO_CATEGORIES: prose
#+HUGO_CUSTOM_FRONT_MATTER: :image https://r2.guolongji.xyz/allinaent/2024/06/a5024b3cfabbbb97c49656e4223d6be8.png

* 人生无常，大肠包小肠

回想起年轻时的情感经历。有很多事情值得深思。

有拒绝我的，有我拒绝的。

曾经因为吾父一句话，让我感觉受到了侮辱。他说你要是追上了某某某，你就是为咱家争光了，做贡献了。听到这
话，本来还有试一试的想法的。瞬间觉得好恶心，后来与那个小时候一起玩的小伙伴简单的聊了两句，什么也没说，
后面就再也不联系了。

我曾经是一个一点也不努力，十分贪玩的人；现在也依然贪玩，做事缺乏长期的坚持，难做到一步一个脚印，稳扎
稳打的前进。儿时的伙伴有很多优秀的女孩。上面那个比较可爱。

另一个更加优秀的看不上我。这一点没什么说的，人的强弱，无论外在还是内在，后天的能力是来源于自我的积累。
比起优秀程度，我不配，也觉得不是一个层次的人，难以融和。正如我很难看上学历很低的，能力很弱的人一样。

人生中因为能力和自信或者经验，情商，错过了一些很好的女孩。好在现在的老婆拯救了我，没有让一个缺点这么
多的我单着太久。媳妇对我很好，我很爱她。我一直不够聪明，或者过去有不少自以为是的小聪明，缺乏努力的行动，该卷不
卷，尤其在学业上吃不得苦。过去受得罪少，现在要多受些罪。

回想起来我失败的几次经历，我发现，人生，是一场很多机会不断来临和溜走的过程。有很多珍贵的东西，本可以
抓住，但没有抓住。每个人都有这种经历。让人十分地感慨甚至心痛。

但是很多事情的结果，很大程度上是心态决定的。长期的事情是心态长期的熏陶形成了习惯，习惯的好坏又塑造了
不同的能力，不同的能力人最终走向不同的阶层。

要不是逆反心理，有不小的可能性我会和另一个女孩子结婚吧。也不一定比现在要好，但是人生的轨迹会有很多不同。

* 关于奋斗工作和学业

心态让人相信或否认某事，很多时候导致了对世界截然不同的看法。而这些看法指导了每一天，做每一件事的方式和
方法。而心态多数时候又是没有对错的。我如果坚持我的心态，那么就按照我的世界观去前进，向自己证明我的想
法是没有错的。

比如面对纯洁的爱情，我不想其中有什么借力或借利之说。我认为两情相悦必是互相欣赏，人的成就中主要靠自己奋
斗来的才是高尚的。有这种心态就要当卷王，你还差的多呢。大多数人能找到什么样的另一半就是靠着前 20 年的奋斗决
定的。

过去的生活是接近躺平的，所以到现在是平庸的；事到如今，最重要的事是如何实现自我的价值并让下一代有更好的环
境和更多的可能性。

* 如何有一个好心态

乾坤未定，你我皆是黑马。要有乐观主义精神，失之东隅，收之桑渝。我现在虽说不是 20 多岁的小伙了，但是我
也有了很多的知识积累和经验。只能不断的参悟和努力，就算没能最终跨越阶级，或者有一些真正的让自己满意的收获，
那也至少能让未来的自己不太后悔。

纸上谈来终觉浅，得知此事要躬行。路虽远，行则将至，祝科学卷，做个不让别人讨厌的 implicit overachiever 。
科学受罪。提高承受努力过程中痛苦的阈值。锻炼一下身体。共勉。
