#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../
#+HUGO_SECTION: post/2024/01
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-01-29 一 09:31]
#+TITLE: 将 mips 4.19 的kvm 迁移到 5.10 上的尝试
#+HUGO_TAGS:
#+HUGO_CATEGORIES: kernel

* 重构

** mmu_notifier_ops

这个结构体要用 5.10 的，所以要重构 4.19 的 virt/kvm/kvm_main.c 当中的方法。

** MMU_INVALIDATE_DOES_NOT_BLOCK

** 方法重构

kvm_mmu_notifier_invalidate_range_start

kvm_mmu_notifier_invalidate_range_end

宏 access_ok

struct mm_struct

__get_user_pages_fast 可能是这个 get_user_pages_fast

fixup_user_fault

7 个问题。


** diff 4.19 5.10 virt/kvm/kvm_main.c

模块参数用 4.19 的。5.10 的先不加，看看会不会有错。


在 C 语言中，__weak 通常被用作一个关键字或是一个宏，用于指示编译器对某个函数或变量进行弱符号（weak symbol）处理。
弱符号是一种在链接过程中具有特殊性质的符号，它允许在链接阶段出现多个同名符号而不会引发冲突。

在 C 语言中，__weak 通常用于嵌入式系统或者一些特定的编译器环境中，用于定义一个弱符号函数或变量。通常情况下，如果
多个文件中定义了同名的全局符号（函数或变量），链接器会产生冲突并报错。但是当某个符号声明为弱符号时，链接器会
优先
选择强符号，如果没有找到强符号，才会选择弱符号。

例如，在嵌入式系统中，我们可能会定义一个默认的错误处理函数，但是这个函数可以被用户自定义的错误处理函数所覆盖。
这时就可以使用__weak 来定义默认的错误处理函数，然后用户可以在其他文件中定义一个同名的函数来覆盖它，而不会产生
链接错误。

具体的语法和使用方法可能会因为编译器和平台的不同而有所差异，因此在具体的代码中使用时需要查阅对应的编译器文档
或者相关的标准库文档以了解其详细的使用方法和限制。

** 需要将 4.19 中的方法改成 5.10 中的方法

virt/kvm/kvm_main.c

+ 一
4.19 的这个
#+begin_src c
static int kvm_mmu_notifier_invalidate_range_start(struct mmu_notifier *mn,
						    struct mm_struct *mm,
						    unsigned long start,
						    unsigned long end,
						    bool blockable)
#+end_src

改成 5.10 的这个
#+begin_src c
static int kvm_mmu_notifier_invalidate_range_start(struct mmu_notifier *mn,
					const struct mmu_notifier_range *range)
#+end_src

改完后，改调用处的。还有实现部分 blockable 参数处理要找一找。


+ 同上
#+begin_src c
static void kvm_mmu_notifier_invalidate_range_end(struct mmu_notifier *mn,
						  struct mm_struct *mm,
						  unsigned long start,
						  unsigned long end)
#+end_src

+ 同上

#+begin_src c
static const struct mmu_notifier_ops kvm_mmu_notifier_ops = {
	.flags			= MMU_INVALIDATE_DOES_NOT_BLOCK,
	.invalidate_range_start	= kvm_mmu_notifier_invalidate_range_start,
	.invalidate_range_end	= kvm_mmu_notifier_invalidate_range_end,
	.clear_flush_young	= kvm_mmu_notifier_clear_flush_young,
	.clear_young		= kvm_mmu_notifier_clear_young,
	.test_young		= kvm_mmu_notifier_test_young,
	.change_pte		= kvm_mmu_notifier_change_pte,
	.release		= kvm_mmu_notifier_release,
};
#+end_src
