#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../
#+HUGO_SECTION: post/2023/11
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2023-11-27 一 10:31]
#+TITLE: 学习ai 的好方式
#+HUGO_TAGS:
#+HUGO_CATEGORIES: ai

* 思路的转变

之前我的思路是买一个显卡，组装一台好机器，装个 linux 的系统，做好环境。一步一步的看文档，写代码。
这个思路是不错，但是可操作性比较差。难度比较大。

现在是 2023 年底了，实际上网上免费的人工智能的学习和白嫖的平台早就有很多了。

人工智能学习平台汇总：https://blog.csdn.net/ruyihen/article/details/121681488

在 google 的 colab 中写代码？免费的 colab 是不能打开终端的，那怎么写代码呢？

不用终端也可以安装依赖库：
https://blog.csdn.net/Drknown/article/details/116780679


云端炼丹：https://v3u.cn/a_id_312

在修改，笔记本设置当中可以选择 T4 GPU ，我现在来看是不需要买什么 GPU 服务器的，只需要学习就可以了。
还有什么呢？课程有了，我要抓住重点。


有很多人取得了不小的成绩，别人的成功你总是倾向于认为是运气，好吧，就算是运气也是实力的一部分。
如果你觉得自己没有什么成长，那也只是因
为自己没有足够的实力。也是因为自己不曾认真付出。努力不一定有结果，但是现阶段的人生绝对不是过去想过
的最好的结果。多是由于自己的经营，而不是别人的毁损，当然我这样说可能不是太公平，但我真的相信，命运
是掌握在人的手里，与其纠结对错和过去，不如把握好现在，只有现在是能够把握住的。还有就是悔恨无益，那
么无须悔恨，因为这样还会浪费时间。人的一生时间这么短，如果想做什么，那就全力去做。总结经验和教训还
是很重要的。不要当“哲学家”了，还是当个“实践家”吧。

https://colab.research.google.com/

这个够用了。把经典的模型学明白，会写代码会调参数，懂得原理。

* colab 的使用

https://www.cnblogs.com/softcorns/p/16369045.html

colab 的使用是比较简单的，虽然有很多的局限性，但是可以直接写代码运行，对于只需要短时间验证的问题，那
就很简单了。也就是说，练习足够，用 google drive ， github 一起来写一些代码吧。人生是要在曲折中前进的
遇到困难是每个人都每天经历的。

关键还是理解这些东西到底是什么。平台是重要的，每个人都是寄生者，寄生于整个人类社会当中。不幸的人千千
万万，幸运的人也同样千千万万。能逆改环境中的不利因素，是强者。能在一生当中取得长久的成功，是智者。

学习太苦太累了，学会苦中作乐，时间长了后就能真见其乐，了解到内涵。
