#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/06
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-06-14 五 11:13]
#+TITLE: 手机、电脑、知识库的同步
#+HUGO_TAGS:
#+HUGO_CATEGORIES: emacs
#+HUGO_CUSTOM_FRONT_MATTER: :image https://r2.guolongji.xyz/allinaent/2024/06/af960550dc8dbdc44674aa00e830fc90.png


* 折腾的目的是为了不折腾或少折腾

需求是第一位的。

一个中专的学服装设计的女生考了阿里数学大赛的全球第十二名。这说明了什么？全部自学，喜欢做难题，有志者
事竟成。

说实话，我折腾的这些东西确实是有用的，能提高工作和学习效率。但是最重要的是什么？最重要的根本，还是工作
和学习本身这些事情上。

所以不是说折腾无用，只是说折腾是提升自我的重要手段但不是最终目的。强干壮根也很重要啊。如果你觉得主
要的东西是无趣的，那肯定是很难做好的。最起码，在兴趣上，你要认为学习的知识和利用工具同样有趣才行。

还有 emby plex 这些功能，是很好用，但是我的需求可心满足的情况上，什么也不加，直接 smb 加 nova video
player ，只要命名规范，一样好看的海报墙。一样可以用 qvideo 在手机上远程观看。也可以快速下载到手机上。

有必要看 4k 电影吗？有必要看 4k 的记录片吗？电视要花很多钱，音响要花很多钱，之前想弄放弃了的。以后
有机会想补上。

+ 但是，我是说但是

你不是时间都不够用吗？说是喜欢数学，物理，人工智能，只是说说吗？是不是很叶公好龙的感觉呢？双链笔记
自从学会了还没有真正的使用。

人生短短几十年，真正热爱的，又有价值的东西是少的，是需要花时间和精力的。去看，去学，去理解，还是见
贤思齐。知行合一，把兴趣转向真正有价值的事情上。

* 同步的方式有很多种

** 开源的坚果云

这个要花钱，可以把双链笔记和文献一起用坚果云同步，一个坚果云的客户端解决问题。还是要安装 zotero 配置。
同时手机也可以同步 orgzly 的数据做 gtd 。

我使用 qnap 自带的 webdav 来同步 zotero，有一个点需要特别注意，那就是权限要使用 webdav 的权限管理方式
而不使用 qnap 的文件权限管理。这样的话，zotero 就不会报偶尔报 http 401 和 http 0 的错误了。偶然发现的
，终于找到解决的办法。

** 开源的网盘服务 nextcloud

nas 上可以搭建这个，可是我为啥不用自带的 qsync （集成到 qfile 中了）呢？nextcloud 确实是很好的开源
方案。也有各个平台的客户端支持，只是我有了自带的 webdav server 和 qsync server ，再用这个感觉多了一些重复
的功能。这个软件我也没有用过。但是在 emacs china 上面有人提到这是一个好工具。

** git

优点是一切免费，缺点是点来点去的比较烦。尤其是在手机上还要手动的 pull 一下。手机上不需要看双链笔记。
因为屏幕太小了，根本看不了。如果有一个好用的平板还行。但是有书和电脑，路上看平板。暂时还不太需要。
手机上这为了做到知行合一。写什么做什么，写的没有做到那就删掉。

快速的可以同步记事本，好用。真心的好用。

** 最适合我的 qsync（放弃）

因为有动态公网 ip 和 ddns 。qsync 的速度很快。而且可以支持版本控制，而且不用 push ， pull 之类的操
作。还可以远程服务端解决版本冲突的问题。这绐我一切尽在掌握，且平时透明的忽略那些没有必要的细节的
问题。

之前的 mydata 我做成了 git 仓库，干脆把 git 仓库删掉，用 qsnyc 来进行同步吧。

之前手机上设置的目录是手机存储下的 mydata 目录，这个目录还保留；qsync 使用新的目录 qsync/mydata/orgmode/gtd
。测试效果一般，手机可以设置同步的最短时间是 5min 的间隔。而 ubuntu 版的桌面客户端是没有设置的。

想要快速同步的话，需要手动点击一下。稍微有一些麻烦。

经过试用， qsync 使用的效果不好。用过才知是坑。

* 最终方案

sudo mount -t davfs -o uid=uos -o gid=uos ${webdavurl} /home/uos/mydata/

orgzly 本身就支持 webdav。平时主要用 org-roam 就够了，不怎么需要用 org-noter 。用起来、用起来、
用起来！

* 叶公好龙

叶公好龙非真好龙，真的想做好一件事，要做到真的热爱。而不是口头上的热爱，所以你懂的。去真正的
热爱。

