#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/03
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-03-27 三 15:34]
#+TITLE: 放过自己，童心隐匿
#+HUGO_TAGS:
#+HUGO_CATEGORIES: prose
#+HUGO_CUSTOM_FRONT_MATTER: :image https://r2.guolongji.xyz/allinaent/2024/06/a5024b3cfabbbb97c49656e4223d6be8.png

* celebrity quote

As human beings, we all mature physically from childhood to adolesscence and then info adulthood,
but our emotions lag behind.

Bernard Sumner

* 放过自己

每个成年人都会感到有时苦痛。这是因为成年人不能像小孩子一样，心情很不好的时候，找家长哭诉。
家长教肓一顿，说：没事，这还不简单，你这么想... ，这么做 ... ，就好了，下次记住了啊，
以后遇到情况了就这么处理... 。

但是成年人和小孩一样，原始的情感动机没有什么不同之处。无非委屈，嫉妒，悔恨，垂头丧气，
高傲自负。而成年人则无人可问，就算问了长辈，自己也不再相信。那么谁才会成为自己的心灵良师呢？——是
“开悟”后的自己。

每个人都会时而因自己能干成某些事而自信心爆膨，时而因为自己干不成某事或在竞争中落败而感到悲
观气愤。

时而做好了某事却像个小丑让他人讨厌，自己空激动。享受了短暂的快乐，却把过程中存在的不足忘的干干净净。
时而因为失败于某事，一厥不振，浪费大量时光用于调节心态。

总而言之，胜骄败馁是心态太差。人的生活成长因素，好的方面可以互相增益；坏的方面，若能改之，甚至比
养成新的好习惯对个人有更大的好处。

* 童心，内心的简单，纯洁与善良

简单的问题用简单的方式解决是可以的。但对于社会，好的出发点并不能直接产生好的结果。成年人的复杂
在于很多简单的好变成了不好。

人之所以有时心中郁结，肯定是遇到了想不通的事。什么事让人想不通？与自己经验和认知不符的事，
比如祁同伟这个人好还是不好？比如李达康这样的好还是不好？比如华为 35 岁被辞退是好还是不好？

正确的答案是没有“好”或“不好”。有的是谁因为这些生活的更好，谁因为这些利益受到了损害。童心于
现实是无用的。人性是恨你有、笑你无，嫌你穷、怕你富。人性自有其光明，也有其阴暗。多做事，少炫
耀。厚积薄发，也是一种成熟吧。有多少发多少，则显蠢笨，亦如卖弄。

正确的逻辑是这样的。反本能，自己吸收到了别人的负能量，像个黑洞一样不反击，照顾这个社会中不足
之处，明白，小可忍，小得小失对于长路大道难事重要的事不过尽是些无用的噪声。

简单说是就高情商。用高级的、人性都喜欢的方式社交、做事。让别人高兴，那么从牛顿第三定理来说，你没有绐别
人施加痛苦之力，那么来自于别人的痛苦之力也会少作用于你。做到不反击是很难的，因为别人骂你，你
一般一定会想立马怼回去，这是本能；而正确的做法是，别人骂，让他骂，他后若知悔，后面显出
大度；他若不悔，自己也无需浪费时间在这个人身上。

童心是我对你好，你不能对我不好；黑就是黑，应矛以消灭；

而高情商的做法，承认世界的多样性；对待大多数对自己无关痛痒的伤害，心中淡然。时间是如此的
有限，以致于把它全花在一件重要的事情上都不一定有成果。而如果低情商，恐怕一般人大量的时间是
空耗的。只有 *“放过了”* 自己，才能成就自己。

cheers, 为了自己开悟，还需不断修行。成熟不是贬义词，多数时刻应尽显成熟，让自己得以远离无所谓的争端；而童
心之中的正义，绝对化的黑白，情澈明亮的理想主义则深埋心底吧。只有夜深人静的时候想一想，恩，我还是
有童心的，它存在。它的存在是让我始终承认这个世界 ultimate form 是真善美的，而简单只有在
经历了一番成熟的历练之后才变成大道至简的。而吾等平平青年，并未进化到如此高阶形态。大道至简，
童心未泯，不是每个人都有资格说的。足不适履，最为可笑...



