#+OPTIONS: author:nil ^:{}
#+HUGO_BASE_DIR: ../../../../../
#+HUGO_SECTION: post/2024/04
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_DRAFT: false
#+DATE: [2024-04-22 一 10:48]
#+TITLE: 线性代数第四章——线性方程组
#+HUGO_TAGS:
#+HUGO_CATEGORIES: exam math

* 克拉默法则

** 方程的求解
线性方程组就是矩阵乘法。两者研究的问题完全等效。矩阵 A ，对应的行列式 D ，当 $D\neq 0$ 时，A 可逆
（说的是方阵）。

$x=A^{-1}b=\frac{1}{D}A^{*}b$ ，此乃求方程组的公式，不知道我之前为啥就没有理解到这一层的东西。后知后觉。

$x_{i}=\frac{|A_{i}|}{|A|},i=1,2,...,n$ ，其中 $|A_{i}| 是 $|A|$ 中的第 i 列元素替换成 b 列向量。

附记：

“克莱姆法则，又译克拉默法则（Cramer's Rule）是线性代数中一个关于求解线性方程组的定理。它适用于变量和
方程数目相等的线性方程组，是瑞士数学家克莱姆（1704-1752）于 1750 年，在他的《线性代数分析导言》中发表的。
其实莱布尼兹〔1693〕，以及马克劳林〔1748〕亦知道这个法则，但他们的记法不如克莱姆。

对于多于两个或三个方程的系统，克莱姆的规则在计算上非常低效；与具有多项式时间复杂度的消除方法相比，其渐近的复
杂度为 O（n·n！）。”

参考：https://blog.csdn.net/hpdlzu80100/article/details/99889327


* 齐次线性方程组

一、表达形式：就是右面全是 0 。

二、什么是齐次线性方程组的解：略

三、齐次线性方程组的基础解系：若 $\xi_{1},\xi_{2},...,\xi_{n-r}$ 线性无关；$Ax=0$ 的任一解向量 $\xi$ 均可由
$\xi_{1},\xi_{2},...,\xi_{n-r}$ 线性表出，则称那组向量为基础解系。

四、$Ax=0$ 解的性质：两个解向量的线性组合仍是解

五、$Ax=0$ 的有解条件（可以不是方阵）：

- 齐次线性方程一定有解，至少有 0 解。
- 只有 0 解，则 $a_{1},a_{2},...,a_{n}$ 线性无关；否则向量组线性相关。

六、基础解系向量个数与 $r(A)$ 的关系

若 $A$ 是 $m \times n$ 矩阵，$r(A)=r <n$ ，则齐次线性方程 $Ax=0$ 存在基础解系，且基础解系
有 $n - r$ 个线性无关解向量组成。即：基础解系向量个数 + r(A)=n （未知数个数）

系数矩阵的秩数 < 增广矩阵的秩数，则无解。

七、$Ax=0$ 的通解：$k_{1}\xi_{1}+k_{2}\xi_{2}+...+k_{n-r}\xi_{n-r}$

八、基础解系和通解的求法：

利用初等行变换不改变线性方程组的解，将 A 初等行变换化成阶梯形矩阵。

阶梯方程的每行中的第一个系数不为零的 r 个未知量 $x_{1},x_{2},...,x_{n}$ 称为独立未知量；而后面的 $n-r$
个未知量 $x_{r+1},...,x_{n}$ 称之为自由未知量。

齐次方程阶梯型的求法：

参考：https://blog.51cto.com/u_15080860/6075403


* 非齐次线性方程组

一、非齐次方程的表达形式：即右则不为 0 。

二、非齐次方程的解（解都竖着写，用列向量表示）

三、非齐次方程 $Ax=b$ 解的性质：

设 $\eta_{1},\eta_{2}$ 是非齐次方程的解，$\xi$ 是非齐次方程的解，则有

$A(\eta_{1}-\eta_{2})=0$

$A(\eta_{1}+k\xi)=b$

四、$Ax=b$ 的有解条件

无解： $r(A)\neq r(A|b)$ $(r(A)+1=r(A|b))$ ，b 不能由 A 的列向量线性表出

有解： $r(A)=r(A|b)$ ，b 可由 A 的列向量组线性表出，
$\{a_{1},a_{2},...,a_{n}\} \cong \{a_{1},a_{2},...,a_{n},b\}$

有唯一解：$r(A)=n$ ，向量组 A 线性无关，增广矩阵线性相关，b 可以由向量组 A 线性表出。

有无穷多解：$r(A)=r(A|b)=r<n$

五、非齐次线性方程组 $Ax=b$ 通解的求法

与求非齐次类似，增广矩阵化成阶梯型。用高斯消元法，将增广矩阵 $(A|b)$ 作初等行变化成阶梯矩阵，先求出齐次
线性方程组的基础解系 $\xi_{1},\xi_{2},...,\xi_{n-r}(r(A)=r)$ ，再求出一个非齐次特解设为 $\eta$ （求 $\eta$ 时，
可取自由未知量为任意值，取 0 值计算即可，代入方程，求得独立未知量，并得 $\eta$ ）则 $Ax=b$ 的通解为：

$k_{1}\xi_{1}{1}+k_{2}\xi_{2}+...+k_{n-r}\xi_{n-r}+\eta$ ，其中 $k_{1},k_{2},...,k_{n-r}$ 是任意常数。

什么是跳跃思维？跳跃思维是偷懒，是很有创造性，但是更容易产生漏洞。所以大多数的时候不要想着跳跃思
维。跳跃的前提是熟练，如果不熟练，是万万不能跳跃的。

[[pdf:~/mydata/orgmode/gtd/2021李永乐复习全书【数学二】.pdf::283++0.00][非齐次线性方程组的通解的求法]]

